package pe.edu.unsch.entities;
// Generated 23/07/2019 03:04:57 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccountProfile generated by hbm2java
 */
@Entity
@Table(name = "account_profile", catalog = "bigdb")
public class AccountProfile implements java.io.Serializable {

	private int idaccountprofile;
	private Account account;
	private Profile profile;
	private Byte status;

	public AccountProfile() {
	}

	public AccountProfile(int idaccountprofile, Account account, Profile profile) {
		this.idaccountprofile = idaccountprofile;
		this.account = account;
		this.profile = profile;
	}

	public AccountProfile(int idaccountprofile, Account account, Profile profile, Byte status) {
		this.idaccountprofile = idaccountprofile;
		this.account = account;
		this.profile = profile;
		this.status = status;
	}

	@Id

	@Column(name = "idaccountprofile", unique = true, nullable = false)
	public int getIdaccountprofile() {
		return this.idaccountprofile;
	}

	public void setIdaccountprofile(int idaccountprofile) {
		this.idaccountprofile = idaccountprofile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idaccount", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idprofile", nullable = false)
	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

}
