package pe.edu.unsch.entities;
// Generated 23/07/2019 03:04:57 AM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Options generated by hbm2java
 */
@Entity
@Table(name = "options", catalog = "bigdb")
public class Options implements java.io.Serializable {

	private int idoptions;
	private Submodule submodule;
	private String name;
	private Byte status;
	private Set<ProfileOption> profileOptions = new HashSet<ProfileOption>(0);

	public Options() {
	}

	public Options(int idoptions, Submodule submodule) {
		this.idoptions = idoptions;
		this.submodule = submodule;
	}

	public Options(int idoptions, Submodule submodule, String name, Byte status, Set<ProfileOption> profileOptions) {
		this.idoptions = idoptions;
		this.submodule = submodule;
		this.name = name;
		this.status = status;
		this.profileOptions = profileOptions;
	}

	@Id

	@Column(name = "idoptions", unique = true, nullable = false)
	public int getIdoptions() {
		return this.idoptions;
	}

	public void setIdoptions(int idoptions) {
		this.idoptions = idoptions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsubmodule", nullable = false)
	public Submodule getSubmodule() {
		return this.submodule;
	}

	public void setSubmodule(Submodule submodule) {
		this.submodule = submodule;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "options")
	public Set<ProfileOption> getProfileOptions() {
		return this.profileOptions;
	}

	public void setProfileOptions(Set<ProfileOption> profileOptions) {
		this.profileOptions = profileOptions;
	}

}
