package pe.edu.unsch.entities;
// Generated 23/07/2019 03:04:57 AM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Submodule generated by hbm2java
 */
@Entity
@Table(name = "submodule", catalog = "bigdb")
public class Submodule implements java.io.Serializable {

	private int idsubmodule;
	private Module module;
	private String name;
	private String url;
	private Byte status;
	private Set<Options> optionses = new HashSet<Options>(0);

	public Submodule() {
	}

	public Submodule(int idsubmodule, Module module) {
		this.idsubmodule = idsubmodule;
		this.module = module;
	}

	public Submodule(int idsubmodule, Module module, String name, String url, Byte status, Set<Options> optionses) {
		this.idsubmodule = idsubmodule;
		this.module = module;
		this.name = name;
		this.url = url;
		this.status = status;
		this.optionses = optionses;
	}

	@Id

	@Column(name = "idsubmodule", unique = true, nullable = false)
	public int getIdsubmodule() {
		return this.idsubmodule;
	}

	public void setIdsubmodule(int idsubmodule) {
		this.idsubmodule = idsubmodule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idmodule", nullable = false)
	public Module getModule() {
		return this.module;
	}

	public void setModule(Module module) {
		this.module = module;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", length = 45)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "submodule")
	public Set<Options> getOptionses() {
		return this.optionses;
	}

	public void setOptionses(Set<Options> optionses) {
		this.optionses = optionses;
	}

}
